### ISSUE TITLE
Social view broken margins on sides

### ISSUE THREAD

**Issue by ezitisitis** [SpinaCMS/Spina#588]
**Issue**
Found that CSS is little bit broken in Social media view.

```css
.horizontal-form .horizontal-form-group {
    ...
    margin: 0 -40px;
    ...
}
```

**Screenshot**
![image](https://user-images.githubusercontent.com/6075434/87236231-17ac7680-c3ef-11ea-90a9-838149418241.png)

**Possible solution**
```css
.horizontal-form .horizontal-form-group {
    ...
    margin: 0 -20px;
    ...
}
```

I'm new to development in Ruby. So maybe you can give me an direction in which I can go to fix it, cause issue is in css, but this css is in gem and that fact is putting me in position where I'm not sure what should I do :)
